# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gops < Formula
  desc "Opinionated deployment helper"
  homepage "https://github.com/mantro/gops"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mantro/gops/releases/download/v0.1.3/gops_0.1.3_Darwin_arm64.tar.gz"
      sha256 "efa082fb9fd195215380fa1a45d0c1b6eb6cf6a858ab207f79fc5bfef7d818e7"

      def install
        bin.install "gops"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mantro/gops/releases/download/v0.1.3/gops_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "7769fee2006667d7c80dd2e984fe7ee2cf07f26e01ed4af54d683e5ce604ccc8"

      def install
        bin.install "gops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mantro/gops/releases/download/v0.1.3/gops_0.1.3_Linux_arm64.tar.gz"
      sha256 "86b8017ffeed6774f2cda8e14d88f6c8b5d0cb09cffa58d7925b6c15a7147c87"

      def install
        bin.install "gops"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mantro/gops/releases/download/v0.1.3/gops_0.1.3_Linux_x86_64.tar.gz"
      sha256 "ce2ec095f5dde4c653a94af77afd899a2303ff3017e8612432097a5d7af15726"

      def install
        bin.install "gops"
      end
    end
  end
end
