# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gops < Formula
  desc "Opinionated deployment helper"
  homepage "https://github.com/mantro/gops"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mantro/gops/releases/download/v0.1.4/gops_0.1.4_Darwin_arm64.tar.gz"
      sha256 "67eb79f9aa26d34e94780b6da2050571a375e151777a9ba74c98d465e2620d16"

      def install
        bin.install "gops"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mantro/gops/releases/download/v0.1.4/gops_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "abcdb1ac90e6379aa591d59e69ffb4fe66bbc9e70e1ce110a0289c85380e1a47"

      def install
        bin.install "gops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mantro/gops/releases/download/v0.1.4/gops_0.1.4_Linux_arm64.tar.gz"
      sha256 "ea35affadf067aaca5f3ad8564ca38b1ce8aba40731df8a46b67792c4a96af49"

      def install
        bin.install "gops"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mantro/gops/releases/download/v0.1.4/gops_0.1.4_Linux_x86_64.tar.gz"
      sha256 "fdf25792e3a1ebea03aa48853f46786bd938ffd0cecc2d9638754c6f57da3c7c"

      def install
        bin.install "gops"
      end
    end
  end
end
